"""Deterministic invoice PDF generation.

Two templates, because the flagship failure is a vendor changing their layout.
``invariant=1`` strips creation dates and document IDs from the output, so the
same invoice produces byte-identical bytes on every run and every machine --
which is what lets a fixture PDF be checked into the repository and compared.

All vendors, addresses and figures are synthetic.
"""

from __future__ import annotations

import io
from decimal import Decimal

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as pdf_canvas

from .state import Invoice

# reportlab is untyped, so pin the page metrics to concrete floats here
# rather than letting Any leak through every layout calculation.
PAGE_WIDTH: float = float(LETTER[0])
PAGE_HEIGHT: float = float(LETTER[1])
INCH: float = float(inch)


def _money(value: str) -> str:
    return f"{Decimal(value):,.2f}"


def render_invoice_pdf(invoice: Invoice) -> bytes:
    """Render an invoice. ``invoice.template`` selects the layout."""
    buffer = io.BytesIO()
    canvas = pdf_canvas.Canvas(buffer, pagesize=LETTER, invariant=1)
    canvas.setTitle(f"Invoice {invoice.number}")
    canvas.setAuthor(invoice.vendor)
    canvas.setSubject("Synthetic invoice generated by the Verity AP sandbox")
    canvas.setCreator("verity-sandbox")

    if invoice.template == "v2":
        _render_v2(canvas, invoice)
    else:
        _render_v1(canvas, invoice)

    canvas.showPage()
    canvas.save()
    return buffer.getvalue()


def _header(canvas: pdf_canvas.Canvas, invoice: Invoice, title: str) -> float:
    y: float = PAGE_HEIGHT - INCH
    canvas.setFont("Helvetica-Bold", 20)
    canvas.drawString(INCH, y, invoice.vendor)
    y -= 0.28 * INCH
    canvas.setFont("Helvetica", 9)
    canvas.drawString(INCH, y, "1 Example Way, Springfield  ·  synthetic test data")
    y -= 0.45 * INCH
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(INCH, y, title)
    return y - 0.35 * INCH


def _line_items(canvas: pdf_canvas.Canvas, invoice: Invoice, y: float) -> float:
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(INCH, y, "SKU")
    canvas.drawString(INCH + 0.9 * INCH, y, "Description")
    canvas.drawRightString(INCH + 4.6 * INCH, y, "Qty")
    canvas.drawRightString(INCH + 5.5 * INCH, y, "Unit")
    canvas.drawRightString(INCH + 6.5 * INCH, y, "Amount")
    y -= 0.06 * INCH
    canvas.line(INCH, y, INCH + 6.5 * INCH, y)
    y -= 0.20 * INCH

    canvas.setFont("Helvetica", 9)
    for item in invoice.line_items:
        canvas.drawString(INCH, y, item.sku)
        canvas.drawString(INCH + 0.9 * INCH, y, item.description)
        canvas.drawRightString(INCH + 4.6 * INCH, y, str(item.quantity))
        canvas.drawRightString(INCH + 5.5 * INCH, y, _money(item.unit_price))
        canvas.drawRightString(INCH + 6.5 * INCH, y, _money(item.amount))
        y -= 0.22 * INCH
    return y


def _render_v1(canvas: pdf_canvas.Canvas, invoice: Invoice) -> None:
    """Template v1: totals block bottom-right, label 'Total Due'."""
    y = _header(canvas, invoice, "INVOICE")

    canvas.setFont("Helvetica", 10)
    for label, value in (
        ("Supplier:", invoice.vendor),
        ("Invoice Number:", invoice.number),
        ("Invoice Date:", invoice.issued_on),
        ("Purchase Order:", invoice.po_number or "-"),
        ("Currency:", invoice.currency),
    ):
        canvas.drawString(INCH, y, label)
        canvas.drawString(INCH + 1.6 * INCH, y, value)
        y -= 0.22 * INCH

    y -= 0.25 * INCH
    y = _line_items(canvas, invoice, y)

    y -= 0.15 * INCH
    canvas.line(INCH + 4.0 * INCH, y, INCH + 6.5 * INCH, y)
    y -= 0.28 * INCH
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(INCH + 4.0 * INCH, y, "Total Due:")
    canvas.drawRightString(INCH + 6.5 * INCH, y, _money(invoice.total))

    if invoice.note:
        canvas.setFont("Helvetica-Oblique", 8)
        canvas.drawString(INCH, INCH * 1.2, invoice.note[:180])


def _render_v2(canvas: pdf_canvas.Canvas, invoice: Invoice) -> None:
    """Template v2: the same invoice, restructured.

    The total moves to the top of the page and is relabelled 'AMOUNT PAYABLE'.
    A deterministic extractor anchored on 'Total Due' will not find it here --
    which is exactly the real-world failure this sandbox exists to reproduce.
    """
    y = _header(canvas, invoice, "TAX INVOICE")

    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(INCH, y, "AMOUNT PAYABLE")
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(INCH + 2.0 * INCH, y, f"{invoice.currency} {_money(invoice.total)}")
    y -= 0.42 * INCH

    canvas.setFont("Helvetica", 10)
    for label, value in (
        ("Supplier:", invoice.vendor),
        ("Ref:", invoice.number),
        ("Order Ref:", invoice.po_number or "-"),
        ("Issued:", invoice.issued_on),
    ):
        canvas.drawString(INCH, y, label)
        canvas.drawString(INCH + 1.6 * INCH, y, value)
        y -= 0.22 * INCH

    y -= 0.25 * INCH
    _line_items(canvas, invoice, y)

    if invoice.note:
        canvas.setFont("Helvetica-Oblique", 8)
        canvas.drawString(INCH, INCH * 1.2, invoice.note[:180])
